name: Build Spring Boot application
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Maven Package
        run: mvn -B clean package -DskipTests
  test:
    name: API test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Set up Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create Newman results directory
        run: mkdir -p newman

      - name : Run Postman tests
        run: |
          mvn spring-boot:run
          newman run "./src/main/resources/postman-collections/api.metadata.json" -r htmlextra --reporter-htmlextra-export newman/n.api.metadata.report.html --reporter-htmlextra-darkTheme > newman/api.metadata.report.html
          newman run "./src/main/resources/postman-collections/api.main.json" -r htmlextra --reporter-htmlextra-export newman/n.api.main.report.html --reporter-htmlextra-darkTheme > newman/api.main.report.html

      - name: Upload tests results
        uses: actions/upload-artifact@v2
        with:
          name: NewmanReports
          path: newman

